/** @type {import('tailwindcss').Config} */
module.exports = {
  purge: {
    enabled: true,
    content: ["./src/**/*.{js,jsx,ts,tsx,vue}"],
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        heading: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        serif: ["Georgia", "Cambria", "Times New Roman", "serif"],
      },
      colors: {
        "brand-primary": "rgb(var(--brand-primary-rgb) / <alpha-value>)",
        "brand-primary-dark": "rgb(var(--brand-primary-dark-rgb) / <alpha-value>)",
        "brand-primary-soft": "rgb(var(--brand-primary-soft-rgb) / <alpha-value>)",
        "brand-accent": "rgb(var(--brand-accent-rgb) / <alpha-value>)",
        primary: "rgb(var(--primary-rgb) / <alpha-value>)",
        "primary-dark": "rgb(var(--primary-dark-rgb) / <alpha-value>)",
        "primary-soft": "rgb(var(--primary-soft-rgb) / <alpha-value>)",
        secondary: "rgb(var(--secondary-rgb) / <alpha-value>)",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        success: "rgb(var(--success-rgb) / <alpha-value>)",
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        surface: "rgb(var(--surface-rgb) / <alpha-value>)",
        "surface-soft": "rgb(var(--surface-soft-rgb) / <alpha-value>)",
        foreground: "rgb(var(--foreground-rgb) / <alpha-value>)",
        section: "rgb(var(--section-rgb) / <alpha-value>)",
        "text-secondary": "rgb(var(--text-secondary-rgb) / <alpha-value>)",
        subtitle: "rgb(var(--subtitle-rgb) / <alpha-value>)",
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        inactive: "rgb(var(--inactive-rgb) / <alpha-value>)",
        tabIndicator: "rgb(var(--tabIndicator-rgb) / <alpha-value>)",
        danger: "rgb(var(--danger-rgb) / <alpha-value>)",
        skeleton: "rgb(var(--skeleton-rgb) / <alpha-value>)",
      },
      borderRadius: {
        card: "16px",
        image: "14px",
        pill: "9999px",
      },
      fontSize: {
        nav: ["10.5px", "16px"],
        eyebrow: ["11px", "16px"],
        metadata: ["12px", "16px"],
        body: ["14px", "20px"],
        product: ["14px", "20px"],
        card: ["15px", "20px"],
        section: ["18px", "24px"],
        page: ["22px", "28px"],
        "3xs": ["11px", "16px"],
        "2xs": ["12px", "16px"],
        xs: ["13px", "18px"],
        sm: ["14px", "18px"],
        base: ["15px", "20px"],
        lg: ["16px", "22px"],
        xl: ["18px", "24px"],
        "2xl": ["20px", "26px"],
      },
    },
  },
};
